org.gradle.jvmargs=-Xmx32G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.06.16
minecraft_version=1.21
minecraft_version_range=[1.21,1.21.1)
neo_version=21.0.20-beta
neo_version_range=[20.5,)
loader_version_range=[2,)

## Mod Properties
mod_id=farts
mod_name=Farts
mod_license=All Rights Reserved
mod_version=2.0.1
mod_group_id=nicusha.farts
mod_authors=Nicusha, TheRealP455W0rd
mod_description=Flatuence.\nnow with 10% more chunk.
