org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.2
minecraft_version_range=[26.1.2, 27.0,)
neo_version=26.2.0.75
neo_version_range=[26.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=farts
mod_name=Farts
mod_license=All Rights Reserved
mod_version=2.0.2.1
mod_group_id=nicusha.farts
mod_authors=Nicusha, TheRealP455W0rd
mod_description=Flatuence.\nnow with 10% more chunk.
issue_tracker_url=https://github.com/NicosaurusRex99/farts/issues
mod_credit=Thanks P455w0rd for that help with networking!
mod_update_json=https://raw.githubusercontent.com/NicosaurusRex99/Nicusha-mod-assets/main/farts.json
mod_url=https://legacy.curseforge.com/minecraft/mc-mods/farts
mod_logo=logo.png
mod_banner=banner.png

## Dependencies
jei_version=30.29.0.202
configured_id=8403595
jer_id=8570081
jei_wg_id=8726646