org.gradle.jvmargs=-Xmx32G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.03.23

# Environment Properties
minecraft_version=1.21.5
minecraft_version_range=[1.21.1, 1.22,)
neo_version=21.5.40-beta
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=farts
mod_name=Farts
mod_license=All Rights Reserved
mod_version=2.0.2.2
mod_group_id=nicusha.farts
mod_authors=Nicusha, TheRealP455W0rd
mod_description=Flatuence.\nnow with 10% more chunk.
