modLoader="javafml"
loaderVersion="[46,)"
license="Ace3 Style BSD"
issueTrackerURL="https://github.com/NicosaurusRex99/farts/issues"
[[mods]]
modId="farts"
version="${file.jarVersion}"
displayName="Farts"
logoFile="logo.png"
credits=""
authors="NicosaurusRex99, TheRealP455W0RD"
description='''
press g for farts
press h for burps
'''
[[dependencies.farts]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.farts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
