modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/NicosaurusRex99/farts/issues/" #optional
[[mods]] #mandatory
modId="farts" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Farts" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/farts" #optional
logoFile="logo.png" #optional
credits="Thanks to TheRealP455w0rd for helping make this mod" #optional
authors="NicosaurusRex99, TheRealP455w0rd" #optional
description='''
press g for farts
press h for burps
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
