modLoader="javafml"
loaderVersion="[40,)"
license="Ace3 Style BSD"
issueTrackerURL="https://github.com/NicosaurusRex99/farts/issues"
[[mods]]
modId="farts"
version="${file.jarVersion}"
displayName="Farts" #mandatory
logoFile="logo.png" #optional
# A text field displayed in the mod UI
credits="Thanks for this example mod goes to Java"
authors="NicosaurusRex99, TheRealP455W0RD"
description='''
press g for farts
press h for burps
'''
[[dependencies.farts]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.farts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
